### ISSUE TITLE
Javi - Clonar el repositorio accediendo desde la rama principal en GitHub en la opción Code ->(HTTPS) en sus PC’s.

### ISSUE THREAD

**Issue by SebaSego** [SebaSego/ISPC-287-Team#4]
![image](https://user-images.githubusercontent.com/91480351/177017175-158d86e2-3ebe-41f1-9728-6b1976cb3e93.png)
Cuando abren Visual Studio Code les sale como opciones de inicio "Clonar el repositorio Git"

Ahí tienen que pegar la dirección copiada desde Git Hub.
Luego tienen que elegir una carpeta en su compu donde se va a clonar el repositorio en su compu.

**Comment by javigoall** [comment]
Listo, pude realizar con exito la actividad. La hice desde la consola utilizando la guia que esta en la plataforma al ultimo del bloque 1. Esta bueno, prueben si pueden de hacerlo con la consola de comandos
